# Generated by Django 6.0.5 on 2026-05-24 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(blank=True, max_length=200)),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('start_year', models.CharField(blank=True, max_length=10)),
                ('end_year', models.CharField(blank=True, help_text='Leave blank if currently studying', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['order', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('start_year', models.CharField(blank=True, max_length=10)),
                ('end_year', models.CharField(blank=True, help_text='Leave blank if current position', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['order', '-start_year'],
            },
        ),
    ]
